#!/bin/bash
case $1 in

    "")         pdflatex -halt-on-error main.tex &&
                bibtex main &&
                pdflatex -halt-on-error main.tex &&
                pdflatex -halt-on-error main.tex &&
                # Do a word count
                printf "Word count " &&
                pdftotext main.pdf &&
                wc -w main.txt | awk '{print $1}' &&
                rm main.txt ;;

    "clean")    rm -f *.aux *.log *.bbl *.blg *.pdf *.out ;;

    "watch")    shift
                ls *.tex *.dot references.bib | entr ./build $@
                reset ;;

    "minimal")  pdflatex -halt-on-error main.tex ;;

    *)          echo "Error. Usage: ./build [ watch | clean | minimal ]?"

esac
