#!/bin/bash
case $@ in

    "")         pdflatex -halt-on-error main.tex &&
                bibtex main &&
                pdflatex -halt-on-error main.tex &&
                pdflatex -halt-on-error main.tex &&
                grep -A 4 -h --no-group-separator "begin{figure" *.tex > \
                    all-fig-code.tex &&
                pdflatex -halt-on-error all_figures.tex &&
                rm all-fig-code.tex &&
                # Do a word count
                printf "Word count " &&
                pdftotext main.pdf &&
                wc -w main.txt | awk '{print $1}' &&
                rm main.txt ;;

    "clean")    rm -f *.aux *.log *.bbl *.blg *.pdf *.out ;;

    "watch")    ls *.tex *.dot references.bib | entr ./build
                reset ;;

    *)          echo "Error. Usage: ./build [ watch | clean ]?"

esac
